name: Deploy Nuxt to self-hosted
on:
  workflow_dispatch:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 198.20.105.79
          username: informix
          password: ${{ secrets.password }}
          local-dir: ./dist/
          server-dir: /public_html/demo/nuxt-studio


# Go to your GitHub repository.
# Click on Settings.
# Click on Secrets and variables > Actions.
# Click New repository secret and add the following secrets:
# FTP_SERVER: Your FTP server address.
# FTP_USERNAME: Your FTP username.
# FTP_PASSWORD: Your FTP password.
